# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.28.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.28.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/alexkim/Developer/regex to DFA"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/alexkim/Developer/regex to DFA"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.28.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.28.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alexkim/Developer/regex to DFA/CMakeFiles" "/Users/alexkim/Developer/regex to DFA//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alexkim/Developer/regex to DFA/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyTarget

# Build rule for target.
MyTarget: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyTarget
.PHONY : MyTarget

# fast build rule for target.
MyTarget/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/build
.PHONY : MyTarget/fast

src/ast.o: src/ast.cpp.o
.PHONY : src/ast.o

# target to build an object file
src/ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/ast.cpp.o
.PHONY : src/ast.cpp.o

src/ast.i: src/ast.cpp.i
.PHONY : src/ast.i

# target to preprocess a source file
src/ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/ast.cpp.i
.PHONY : src/ast.cpp.i

src/ast.s: src/ast.cpp.s
.PHONY : src/ast.s

# target to generate assembly for a file
src/ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/ast.cpp.s
.PHONY : src/ast.cpp.s

src/iterator.o: src/iterator.cpp.o
.PHONY : src/iterator.o

# target to build an object file
src/iterator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/iterator.cpp.o
.PHONY : src/iterator.cpp.o

src/iterator.i: src/iterator.cpp.i
.PHONY : src/iterator.i

# target to preprocess a source file
src/iterator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/iterator.cpp.i
.PHONY : src/iterator.cpp.i

src/iterator.s: src/iterator.cpp.s
.PHONY : src/iterator.s

# target to generate assembly for a file
src/iterator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/iterator.cpp.s
.PHONY : src/iterator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/scanner.o: src/scanner.cpp.o
.PHONY : src/scanner.o

# target to build an object file
src/scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/scanner.cpp.o
.PHONY : src/scanner.cpp.o

src/scanner.i: src/scanner.cpp.i
.PHONY : src/scanner.i

# target to preprocess a source file
src/scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/scanner.cpp.i
.PHONY : src/scanner.cpp.i

src/scanner.s: src/scanner.cpp.s
.PHONY : src/scanner.s

# target to generate assembly for a file
src/scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyTarget.dir/build.make CMakeFiles/MyTarget.dir/src/scanner.cpp.s
.PHONY : src/scanner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyTarget"
	@echo "... src/ast.o"
	@echo "... src/ast.i"
	@echo "... src/ast.s"
	@echo "... src/iterator.o"
	@echo "... src/iterator.i"
	@echo "... src/iterator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scanner.o"
	@echo "... src/scanner.i"
	@echo "... src/scanner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

